# Generated by Django 3.1.7 on 2021-03-02 05:42

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fill_types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='fill_type_attributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('fill_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.fill_types')),
            ],
        ),
        migrations.CreateModel(
            name='areas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('points', django_mysql.models.ListTextField(models.IntegerField(), size=2)),
                ('fill_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.fill_types')),
            ],
        ),
        migrations.CreateModel(
            name='area_type_attributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.areas')),
                ('fill_type_attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.fill_type_attributes')),
            ],
        ),
    ]
